### ISSUE TITLE
Encountered a hold-up when system changed times (synchronizing with an outside source)

### ISSUE THREAD

**Issue by orrinjelo** [erikzenker/inotify-cpp#28]
Using inotify-cpp, got trapped where

Line 286 of Inotify.cpp:
`bool Inotify::onTimeout(time_t eventTime)
{
    return (mLastEventTime + mEventTimeout) > eventTime;
}`

in the case _mLastEventTime_ somehow was a value much later than _eventTime_.  It turns out that there was a system time change at some point when Inotify was being used and caused the _mLastEventTime_ to hold on to the old (and distant future) value.  This resulted on the below if statement always returning true and never updating _mLastEventTime_ to something reasonable.

Line 240 of Inotify.cpp:
`   // Filter events
        for (auto eventIt = events.begin(); eventIt < events.end(); ++eventIt) {
            FileSystemEvent currentEvent = *eventIt;
            if (onTimeout(currentEventTime)) {
                events.erase(eventIt);
                mOnEventTimeout(currentEvent);

            } else if (isIgnored(currentEvent.path.string())) {
                events.erase(eventIt);
            } else {
                mLastEventTime = currentEventTime;
                mEventQueue.push(currentEvent);
            }
}`

I propose this change for your consideration: instead of using _time(NULL)_ use _std::chrono::steady_clock_, which represents a monotonic clock. 

Lines 186 of Inotify.cpp: 
`time_t currentEventTime = time(NULL);`

211:
` currentEventTime = time(NULL);`

**Comment by erikzenker** [comment]
I opened a pull request https://github.com/erikzenker/inotify-cpp/pull/29
