### ISSUE TITLE
watchDirectoryRecursively. Fix if condition

### ISSUE THREAD

**Issue by et-nik** [erikzenker/inotify-cpp#45]
Hm, I think here must be `&&` instead `||`
https://github.com/erikzenker/inotify-cpp/blob/master/src/Inotify.cpp#L108

With `||` paths.push_back(currentPath) don't called.

**Comment by erikzenker** [comment]
You are right. There exists a regression that was introduced by refactorings recently. Thank you for reporting the bug. I'll work on a unit test to reproduce the bug.
