### ISSUE TITLE
[REQUEST] Add interface for std::filesystem as well

### ISSUE THREAD

**Issue by ChristianJacobsen** [erikzenker/inotify-cpp#51]
I stumbled across this library and it's exactly what I need for my project!
I use boost for command line parsing, but I use the std::filesystem api instead of boost's.
Do you have any plans to add support for this or would you like me to do it?

Merry Christmas!

**Comment by erikzenker** [comment]
Hi Christian, I had no plans to update from `boost:filesystem` to `std::filesystem` up to now. Switching to the std version would mean to raise the c++ std version to C++17. Currently, only c++11 is necessary. Is `boost::filesystem` a no go for you? I mean you already use the boost library. You could write a function which converts from and to `boost::filesystem` (just thinking loud).

Usually, I am a big fan of updating to newest and greates, but I think C++17 and not yet well adopted from a lot of programmers. What do you think?

**Comment by ChristianJacobsen** [comment]
I have no problem using the `boost::filesystem` - I would just like to stick with the `std` library whenever possible. I was originally thinking of wrapping the `std::filesystem` parts in `#ifdef`s with a minimum standard of C++17, but I feel like that would, most likely, duplicate a majority of the code as well as making it 'impossible' to read.

I will see if I can't use Boost's filesystem instead as you are, rightfully, saying; I'm already using Boost - so why not? :)

Thanks for your quick reply!

**Comment by schreiberstein** [comment]
I would second this request.
One less library to link against / need to ship.
I hope I will see this feature some day.

**Comment by erikzenker** [comment]
Maybe its time to update to c++17?

**Comment by schreiberstein** [comment]
YES!
Time for s/boost::filesystem/std::filesystem 👍🏻 
#ifdef guards are ugly, but they could work in this instance.
I have not looked much into your code, but as far as I remember, std::filesystem::path boost::filesystem::path should be mostly compatible. So maybe some "using" / typedef magic could automatically switch between std::filesystem and boost::filesystem to reduce the total number of ifdefs required for retaining backwards compatibility to C++11 ?
Not sure.

**Comment by erikzenker** [comment]
The library was updated to c++17 and by that to std::filesystem
