### ISSUE TITLE
multiple events at return of epoll_wait 

### ISSUE THREAD

**Issue by rasmus116** [erikzenker/inotify-cpp#59]
Theoretically, 10 events can return at the same time from epoll_wait. 
```cpp
auto nFdsReady = epoll_wait(mEpollFd, mEpollEvents, MAX_EPOLL_EVENTS, timeout);
```
In every iteration for these events data is reading into same memory address(`eventBuffer.data()`).
```cpp
    for (auto n = 0; n < nFdsReady; ++n) {
        if (mEpollEvents[n].data.fd == mStopPipeFd[mPipeReadIdx]) {
            break;
        }

        length = read(mEpollEvents[n].data.fd, eventBuffer.data(), eventBuffer.size());
        if (length == -1) {
            mError = errno;
            if(mError == EINTR){
                break;
            }
        }
    }
```
Under these circumstances data of 'eventBuffer' is overwritten for each iteration of for loop.

That condition may be impossible for that project, but as a epoll_wait implementation it seems to be a problem.

**Comment by erikzenker** [comment]
Hi @rasmus116 , 
thank you very much for reporting that issue. That might be fixable easily by reducing the max epoll events to 1, right?

Adding more event buffers would also be a solution, but needs more changes for the first shot.

**Comment by erikzenker** [comment]
@rasmus116 ,I created a pull request for your issue. Would you like to make a review?

**Comment by rasmus116** [comment]
It looks ok 👍 .

**Comment by erikzenker** [comment]
thx :+1:
