### ISSUE TITLE
You forget to put your name and the year on your LICENSE file

### ISSUE THREAD

**Issue by elvisdukaj** [erikzenker/inotify-cpp#67]
https://github.com/erikzenker/inotify-cpp/blob/d81ab7670a995680daf1d9fb2de34f1cfd3784f9/LICENSE#L3

**Comment by erikzenker** [comment]
You are right! Thank you for the hint. I'll fix it!

**Comment by erikzenker** [comment]
Fixed by #68. Thanks again for reporting!
